name: rick_morty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.1
  flutter_mobx: ^2.2.1+1
  mobx: ^2.4.0
  flutter_map: ^7.0.2
  hive_ce: ^2.8.0+2
  hive_ce_flutter: ^2.1.0
  http: ^1.2.2
  get_it: ^8.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mobx_codegen: ^2.6.2
  build_runner: ^2.4.13
  hive_ce_generator: ^1.8.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
