// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:rick_morty/core/hive/adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CharacterModelAdapter());
    registerAdapter(LocationModelAdapter());
  }
}
